apiVersion: v1
kind: Service
metadata:
  name: chrome
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: chrome
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.chrome.type }}
  ports:
    - port: {{ .Values.service.chrome.port }}
      targetPort: {{ .Values.service.chrome.port }}
      protocol: TCP
      name: http
  selector:
    app: chrome
    app.kubernetes.io/instance: {{ .Release.Name }} 