apiVersion: v1
kind: ConfigMap
metadata:
  name: hoarder-configuration
  namespace: {{ .Release.Namespace }}
data:
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }} 