apiVersion: v1
kind: Service
metadata:
  name: meilisearch
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: meilisearch
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.meilisearch.type }}
  ports:
    - port: {{ .Values.service.meilisearch.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: meilisearch
    app.kubernetes.io/instance: {{ .Release.Name }} 