apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: hoarder-web
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.service.web.type }}
  ports:
    - port: {{ .Values.service.web.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: hoarder-web
    app.kubernetes.io/instance: {{ .Release.Name }} 